export default{
    POSTS:'POSTS',
    LOADING:'LOADING',
    ERROR:'ERROR',
    MORE:'MORE',
    LESS:'LESS',
    SHOW_POST:'SHOW_POST',
    ON_LIKE:'ON_LIKE',
    ON_LOVE:'ON_LOVE',
    NEW_COMMENT:'NEW_COMMENT',
    NEW_POST:'NEW_POST',
    CHAT_MESSENGER:'CHAT_MESSENGER',
    NEW_CHAT:'NEW_CHAT'
}